ci: auth-server 배포 스크립트 수정

diff --git a/.github/workflows/auth-server-ci.yml b/.github/workflows/auth-server-ci.yml
--- a/.github/workflows/auth-server-ci.yml
+++ b/.github/workflows/auth-server-ci.yml
@@ -31,7 +31,10 @@ jobs:
           node-version: ${{ matrix.node-version }}
 
       - name: Inject ENV_FILE
-        run: echo "${{ env.ENV_FILE }}" > src/backend/auth-server/.env.production
+        run: |
+          printf "%s" "${{ secrets.ENV_FILE }}" > src/backend/auth-server/.env.production
+          ls -lah src/backend/auth-server
+          cat src/backend/auth-server/.env.production || echo "File not found"
 
       - name: Log in to DockerHub
         uses: docker/login-action@v3
